directories:
  output: dist-installer
  buildResources: build
appId: com.RafaRadio
extraResources:
  - filter:
      - firebase-applet-config.json
productName: RafaRadio
files:
  - filter:
      - src/**/*
      - node_modules/**/*
      - package.json
win:
  target: nsis
mac:
  target: dmg
linux:
  target: AppImage
electronVersion: 43.0.0
